### ISSUE TITLE
[Godot] How to Add Geometry and Textures to a Scene?

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#19]
@Luka-sama:  please research how external geometry can be added to a Godot project.

* [x] Which file types are permitted for geometry?
* [x] Which file types are permitted for textures?
* [x] How can procedural textures be mapped to a geometry?
* [x] Are there any restrictions to mind?

Please post your answers to these questions in this issue for reference.

**Comment by Luka-sama** [comment]
* glTF 2.0, DAE (COLLADA), OBJ (Wavefront), ESCN, FBX
* .bmp, .dds, .exr, .hdr, .jpg (.jpeg), .png, .tga, .svg, .svgz, .webp. You can also add texture directly to the model (e. g. GLB format).
* You can use [this tool](https://github.com/RodZill4/material-maker) to create procedural textures. It generates all necessary files to use procedural textures in Godot.
* It depends on chosen file format (see e. g. note for glTF below).

See following links for more details:
* [Importing scenes](https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_scenes.html)
* [Importing images](https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_images.html)

Godot recommends glTF 2.0 for 3D-models (text (.gltf) or binary (.glb) format). This format can also contain textures. This format is open source and supported by Blender (since 2.80 built-in support), so I think we could use this format?

Note to glTF:
> Blender does not export emissive textures with the glTF file. If your model uses one, it must be brought in separately.
> 
> By default, Blender has backface culling disabled on materials and will export materials to match how they render in Blender. This means that materials in Godot will have their cull mode set to Disabled. This can decrease performance since backfaces will be rendered, even when they are being culled by other faces. To resolve this, enable Backface Culling in Blender's Materials tab, then export the scene to glTF again.

**Comment by kevinmatthes** [comment]
Thanks!  Please note these information as well in a reference file of this repository.
