### ISSUE TITLE
[Geometry] Export Geometry in all Formats to New Geometry Repository

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#25]
Please export the geometry of your recent Blender projects to https://github.com/StarSimVR/geometry using the following file formats:

* [x] OBJ
* [x] gITF 2.0

Save the resulting files in the respective directories by naming them intuitively understandable.  Please mind that Godot expects the y axis to be the Up Vector!

@Ranplax

**Comment by NiklasLeukroth** [comment]
Since exporting and object using gitf2 automatically applies the texture onto it, without further needing the texture file itself and godot recommending the use of gitf2, i would propose gitf2 as our default. Using obj, we would have to include the textures themselves everytime we use the object, creating unnecessary overhead in my opinion. @kevinmatthes @Luka-sama what do you think?

**Comment by kevinmatthes** [comment]
I agree with you that this utility function simplifies the geometry definition regarding the usage in Godot.  But in my opinion, we should add the further formats, as well, since this might benefit the definition of further objects.

In case we should need an object resembling the shape of Jupiter, we would not need to remove the texture from the gITF 2.0 geometry but instead just import the Wavefront model and apply the new texture to it.  This might be faster.  Hence, we should keep the Wavefront geometry up-to-date, as well.
