### ISSUE TITLE
[General] Add DLL Support

### ISSUE THREAD

**Issue by NiklasLeukroth** [StarSimVR/backlog#43]
- [x] Add DLL Export functionality
- [x] Merge into main branch (Adjustments to the makefile etc. have to be made)

**Comment by kevinmatthes** [comment]
Please also test if the DLL works as it should.

**Comment by kevinmatthes** [comment]
Please post the compiler call for your DLL compilation here.

**Comment by kevinmatthes** [comment]
I just merged the changes from my fork to the main branch; I am still missing the compilation instructions for Windows.  Please adjust your version of the Makefile accordingly.

Since the whole build routine now depends on GNU Octave, you can edit the Makefile such that it will exclusively compile the Windows DLL.  I will translate this into GNU Octave as soon as you edited the build instructions.

**Comment by NiklasLeukroth** [comment]
The makefile has been adjusted accordingly, let me know, if you need further information

**Comment by kevinmatthes** [comment]
Thanks!
