### ISSUE TITLE
[VR] Make Warps Smoother

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#63]
Please adjust the warping such that it is presented with smoother changes of the displayed scene.

**Comment by NiklasLeukroth** [comment]
Since the smoother transition will increase the motion sickness, instead of decreasing it, it will not be imlemented. However, marking the planet to which the player will be teleported should help reduce the sickness, since a visual indication is beeing set. This however will be discussed in a seperate issue
